/*
 * NVIC_Driver.cpp
 *
 * STM32F407 Bare-Metal NVIC Driver
 *
 * Created on: 19-Jul-2026
 * Author: jolap
 *
 * Purpose:
 *   Implementation of the ARM Cortex-M4 Nested Vectored Interrupt Controller
 *   helper routines for enabling, disabling, pending, and prioritizing IRQs.
 *
 * State Machine:
 *   Interrupt request -> priority check -> pending/active handling -> ISR dispatch.
 *
 * RM0090 Reference:
 *   ARM Cortex-M4 Generic User Guide - Nested Vectored Interrupt Controller
 */

 /*********************************************************************
  *                      NVIC Driver Design
  *
  * The Nested Vectored Interrupt Controller (NVIC) is an integral
  * component of the ARM Cortex-M4 processor responsible for managing
  * all external interrupts and exceptions. It enables the processor
  * to respond to asynchronous events generated by on-chip peripherals
  * and external hardware with minimal latency.
  *
  * The NVIC provides hardware support for interrupt prioritization,
  * interrupt nesting, preemption, pending state management, and
  * software-triggered interrupts. It allows higher-priority
  * interrupts to interrupt lower-priority interrupt service routines,
  * ensuring deterministic real-time behavior.
  *
  * The STM32F407 supports up to 82 maskable external interrupts,
  * each associated with an Interrupt Request Number (IRQn).
  *
  * The NVIC contains several register groups:
  *
  *      • Interrupt Set-Enable Registers (ISER)
  *      • Interrupt Clear-Enable Registers (ICER)
  *      • Interrupt Set-Pending Registers (ISPR)
  *      • Interrupt Clear-Pending Registers (ICPR)
  *      • Interrupt Active Bit Registers (IABR)
  *      • Interrupt Priority Registers (IPR)
  *      • Software Trigger Interrupt Register (STIR)
  *
  * The NVIC driver provides APIs to enable or disable interrupts,
  * configure interrupt priorities, manage pending interrupts, and
  * support software-generated interrupt requests.
  *
  *********************************************************************
  *                  Interrupt Management State Machine
  *
  *              Peripheral Event Occurs
  *                      │
  *                      ▼
  *           Peripheral Sets IRQ Request
  *                      │
  *                      ▼
  *          Interrupt Reaches NVIC
  *                      │
  *                      ▼
  *          Check Interrupt Enabled
  *                      │
  *          ┌───────────┴───────────┐
  *          │                       │
  *         No                      Yes
  *          │                       │
  *          ▼                       ▼
  *    Ignore Request        Check Priority
  *                                  │
  *                                  ▼
  *                     Higher Priority Than Current?
  *                                  │
  *                  ┌───────────────┴──────────────┐
  *                  │                              │
  *                 No                             Yes
  *                  │                              │
  *                  ▼                              ▼
  *          Pending State                 Preempt Current ISR
  *                  │                              │
  *                  ▼                              ▼
  *                Wait                  Load ISR Vector
  *                                             │
  *                                             ▼
  *                                     Execute ISR
  *                                             │
  *                                             ▼
  *                                   Return From Interrupt
  *
  *********************************************************************
  *             Software Interrupt State Machine
  *
  *          Select Interrupt Number
  *                      │
  *                      ▼
  *          Write STIR Register
  *                      │
  *                      ▼
  *          NVIC Sets Pending Bit
  *                      │
  *                      ▼
  *       Scheduler Evaluates Priority
  *                      │
  *                      ▼
  *          Execute Corresponding ISR
  *                      │
  *                      ▼
  *          ISR Completes Execution
  *                      │
  *                      ▼
  *        Return To Previous Context
  *
  *********************************************************************
  *                  Driver Responsibilities
  *
  * • Enable external interrupts.
  * • Disable external interrupts.
  * • Set interrupt priorities.
  * • Read interrupt active status.
  * • Set interrupt pending state.
  * • Clear interrupt pending state.
  * • Generate software interrupts.
  * • Support interrupt nesting.
  * • Support interrupt preemption.
  *
  * ARM Cortex-M4 Reference:
  * Chapter 4 - Nested Vectored Interrupt Controller (NVIC)
  *
  *********************************************************************/

#include "NVIC_Driver.h"

 /*********************************************************************
  *                  Enable IRQ
  *********************************************************************/
void NVIC::enableIRQ(uint8_t irq)
{
	if (irq < 240) // Check if the IRQ number is valid
	{
		NVIC_REG->ISER[irq / 32] = (1 << (irq % 32)); // Set the corresponding bit in ISER
	}
}
/*********************************************************************
 *                  Disable IRQ
 *********************************************************************/
void NVIC::disableIRQ(uint8_t irq)
{
	if (irq < 240) // Check if the IRQ number is valid
	{
		NVIC_REG->ICER[irq / 32] = (1 << (irq % 32)); // Clear the corresponding bit in ICER
	}
}
/*********************************************************************
 *                  Set Pending IRQ
 *********************************************************************/
void NVIC::setPendingIRQ(uint8_t irq) {
	if (irq < 240) // Check if the IRQ number is valid
	{
		NVIC_REG->ISPR[irq / 32] = (1 << (irq % 32)); // Set the corresponding bit in ISPR
	}
}
/*********************************************************************
 *                  Clear Pending IRQ
 *********************************************************************/
void NVIC::clearPendingIRQ(uint8_t irq) {
	if (irq < 240) // Check if the IRQ number is valid
	{
		NVIC_REG->ICPR[irq / 32] = (1 << (irq % 32)); // Clear the corresponding bit in ICPR
	}
}
/*********************************************************************
 *                  Get Active IRQ
 *********************************************************************/	
bool NVIC::getActiveIRQ(uint8_t irq) {
	if (irq < 240) // Check if the IRQ number is valid
	{
		return (NVIC_REG->IABR[irq / 32] & (1 << (irq % 32))) != 0; // Return the status of the corresponding bit in IABR
	}
	return false; // Return false if the IRQ number is invalid
}
/*********************************************************************
 *                  Check IRQ Enabled Status
 *********************************************************************/
bool NVIC::isIRQEnabled(uint8_t irq) {
	if (irq < 240)
	{
		return (NVIC_REG->ISER[irq / 32] & (1 << (irq % 32))) != 0;
	}
	return false;
}
/*********************************************************************
 *                  Set IRQ Priority
 *********************************************************************/
void NVIC::setPriority(uint8_t irq, uint8_t priority) {
	if (irq < 240) // Check if the IRQ number is valid
	{
		NVIC_REG->IPR[irq] = static_cast<uint8_t>((priority & 0xF) << 4);
	}
}

