@startuml Project_Architecture

title STM32F407 Bare-Metal C++ Driver Library Architecture

package "Application Layer" {
    class main.cpp
    class LED_Blink
    class Button
    class UART_Test
}

package "Driver Layer" {

    class GPIO
    class RCC
    class EXTI
    class SysTick
    class USART
    class SPI
    class I2C
    class CAN
    class TIMER
    class DMA
    class FLASH
    class WATCHDOG
}

package "CMSIS / Register Layer" {
    class "stm32f407xx.h"
}

package "Hardware" {
    class GPIOA
    class GPIOB
    class GPIOC
    class GPIOD
    class RCC_REG
    class USART_REG
    class SPI_REG
    class I2C_REG
    class CAN_REG
}

main.cpp --> GPIO
main.cpp --> USART
main.cpp --> SysTick

LED_Blink --> GPIO
Button --> GPIO
UART_Test --> USART

GPIO --> RCC
USART --> RCC
SPI --> RCC
I2C --> RCC
CAN --> RCC
EXTI --> RCC
SysTick --> RCC
TIMER --> RCC
DMA --> RCC

GPIO --> "stm32f407xx.h"
RCC --> "stm32f407xx.h"
USART --> "stm32f407xx.h"
SPI --> "stm32f407xx.h"
I2C --> "stm32f407xx.h"
CAN --> "stm32f407xx.h"
EXTI --> "stm32f407xx.h"
SysTick --> "stm32f407xx.h"

"stm32f407xx.h" --> GPIOA
"stm32f407xx.h" --> GPIOB
"stm32f407xx.h" --> GPIOC
"stm32f407xx.h" --> GPIOD
"stm32f407xx.h" --> RCC_REG
"stm32f407xx.h" --> USART_REG
"stm32f407xx.h" --> SPI_REG
"stm32f407xx.h" --> I2C_REG
"stm32f407xx.h" --> CAN_REG

@enduml